package com.example.cab302assignment.model;

import com.example.cab302assignment.model.enums.SensitiveDataType;

import java.util.EnumMap;
import java.util.Map;

/**
 * Represents the outcome of passing a user's prompt through the redaction engine.
 * This class holds the sanitized text, the total number of sensitive entities found,
 * and a detailed breakdown of which specific types of sensitive data were detected.
 */
public class RedactionResult {

    private int resultId;
    private int promptId;
    private String redactedText;
    private int totalDetections;
    private Map<SensitiveDataType, Integer> typeCounts = new EnumMap<>(SensitiveDataType.class);

    /**
     * Default constructor required for database operations and serialization.
     */
    public RedactionResult() {
    }

    /**
     * Constructs a new RedactionResult with the core output data from the redaction engine.
     *
     * @param redactedText    The safe, sanitized version of the original prompt.
     * @param totalDetections The overall count of sensitive entities found and redacted.
     * @param typeCounts      A map detailing the count of each specific {@link SensitiveDataType} detected.
     */
    public RedactionResult(String redactedText, int totalDetections, Map<SensitiveDataType, Integer> typeCounts) {
        this.redactedText = redactedText;
        this.totalDetections = totalDetections;
        if (typeCounts != null) this.typeCounts.putAll(typeCounts);
    }

    /**
     * Gets the unique database identifier for this redaction result.
     * @return The result ID.
     */
    public int getResultId() { return resultId; }


    /**
     * Sets the unique database identifier for this redaction result.
     * @param resultId The ID generated by the database.
     */
    public void setResultId(int resultId) {this.resultId = resultId;}

    /**
     * Gets the unique database identifier of the original prompt this result belongs to.
     * @return The prompt ID.
     */
    public int getPromptId() { return promptId; }

    /**
     * Sets the unique database identifier of the original prompt this result belongs to.
     * @param promptId The associated prompt ID.
     */
    public void setPromptId(int promptId) { this.promptId = promptId; }

    /**
     * Gets the safe, sanitized text generated by the redaction engine.
     * @return The text with sensitive information replaced by redaction markers.
     */
    public String getRedactedText() { return redactedText; }

    /**
     * Sets the sanitized text.
     * @param redactedText The safe text to store.
     */
    public void setRedactedText(String redactedText) { this.redactedText = redactedText; }

    /**
     * Gets the total number of sensitive items that were redacted.
     * @return The total count of detections.
     */
    public int getTotalDetections() { return totalDetections; }

    /**
     * Sets the total number of sensitive items that were redacted.
     * @param totalDetections The total count of detections.
     */
    public void setTotalDetections(int totalDetections) { this.totalDetections = totalDetections; }

    /**
     * Gets the detailed breakdown of the types of sensitive data found.
     * @return A map linking each detected {@link SensitiveDataType} to how many times it appeared.
     */
    public Map<SensitiveDataType, Integer> getTypeCounts() { return typeCounts; }

    /**
     * Sets the detailed breakdown of sensitive data types.
     * Ensures the internal map is always initialized as an {@link EnumMap} to prevent null pointers.
     *
     * @param typeCounts The map of data types and their counts.
     */
    public void setTypeCounts(Map<SensitiveDataType, Integer> typeCounts) {
        this.typeCounts = typeCounts == null ? new EnumMap<>(SensitiveDataType.class) : typeCounts;
    }
}
